### ISSUE TITLE
Support `useTranslate` with await for React server component

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-cli#71] opened 2024-02-26 13:01 UTC
Usage of useTranslate with await like this `const { t } = await useTranslate()` or `const { t } = await useTranslate('namespace')`.

I've created a branch with failing tests: [cynthia/fix-react-with-await](https://github.com/tolgee/tolgee-cli/tree/cynthia/fix-react-with-await)

**Comment by cyyynthia** [comment] 2024-03-11 10:04
Closing this as can't reproduce.

**Closed by cyyynthia** 2024-03-11 10:04 UTC
Labels: bug, invalid
